Fourth app
violentr/reactjs-workshop pull request #4
Opened 2019-05-06 19:37 UTC by violentr

Create routes, pages (views)
   - Main (/)
   - All Products (/products)
   - Individual Product(/products/:id)
   - About(/about)
   - Checkout(/checkout)
  - Not Found
Refactor routes
  - Make plain routes no JSX

Disable Basket but when no products added to basket

2019-05-07 09:35 UTC, index01d requested changes
Предлагаю немного переструктурировать дерево проекта.

Исходный код самого приложения нужно переместить в src (константы, контейнеры, контекст это ведь всё тоже исходный код приложения). Карточку и её составляющие можно поместить в директорию ProductCard (index.js, Title.js, ...), составленые части каталога в Catalog (или если компонент только один то Catalog.js) и.т.д.; удалить неиспользуемые теперь файлы (e.g.: Github, Helper). Для общих и реиспользуемых компонентов создать папку `src/shared`, специфичные компоненты переместить поближе к страницам `src/views/соответствующая страница`

2019-05-07 09:35 UTC, index01d commented on Week-1/containers/CartContainer.js
> +    this.showBasket = this.showBasket.bind(this)
можно использовать https://babeljs.io/docs/en/babel-plugin-syntax-class-properties, чтобы подсократить количество кода здесь, в целом в 2019 можно уже смело использовать этот функционал

2019-05-07 09:35 UTC, index01d commented on Week-1/src/Catalog.js
> +            {...product} {...options} {...props}
ничего криминального, но выглядит как плохой знак

2019-05-07 09:35 UTC, index01d commented on Week-1/src/ProductCard.js
> +    <TextBox {...props}/>
было правильно, стало неправильно. Конкретный компонент не должен знать о специфичной структуре данных (о продукте)

2019-05-07 11:40 UTC, violentr commented on Week-1/containers/CartContainer.js
> +    this.showBasket = this.showBasket.bind(this)
@index01d Не очень понятно что именно здесь имеется ввиду ?
как это мне поможет ?

2019-05-07 11:42 UTC, violentr commented on Week-1/src/ProductCard.js
> +    <TextBox {...props}/>
Здесь я питался реализовать индивидуальную страничку товара, компонент был подходящем местом для линка к страничке
что именно я сделал не верно и как мог би улучшить ?

2019-05-07 15:52 UTC, index01d commented on Week-1/containers/CartContainer.js
> +    this.showBasket = this.showBasket.bind(this)
вместо bind, метод ниже будет определяться как 
```
showBasket = (args) => {
  // тело метода
}
```

2019-05-07 15:53 UTC, index01d commented on Week-1/src/ProductCard.js
> +    <TextBox {...props}/>
здесь неверно то, что целиком объект продукта отправляется в TextBox, в Image, а эти компоненты не должен разбирать объект продукта

2019-05-09 07:02 UTC, index01d requested changes

2019-05-09 07:02 UTC, index01d commented on Week-1/src/containers/CartContainer.js
>      this.props.history.push(`${checkoutPath()}`)
интерполяция не нужна, можно просто `push(checkoutPath())`

2019-05-09 07:51 UTC, violentr commented on Week-1/src/containers/CartContainer.js
>      this.props.history.push(`${checkoutPath()}`)
@index01d исправил

2019-05-10 07:32 UTC, index01d requested changes
Подсказка: чтобы состояние корзины не терялось при переходах на клиенте нужно обернуть приложение в App.js целиком в CartContainer.

2019-05-10 07:32 UTC, index01d commented on Week-1/src/containers/CartContainer.js
> +    this.props.history.push({pathname: checkoutPath(), state: this.state})
список продуктов нужно передавать с помощью контекста, не следует передавать данные в состоянии роутера

2019-05-10 08:50 UTC, violentr commented
> Подсказка: чтобы состояние корзины не терялось при переходах на клиенте нужно обернуть приложение в App.js целиком в CartContainer.

@index01d не понятно что надо сделать, что обернуть ? куда ?
получаешь кучу ошибок и никакого результата пытался обернуть вообще нето ..

2019-05-11 07:35 UTC, index01d requested changes

2019-05-11 07:35 UTC, index01d commented on Week-1/src/containers/CartContainer.js
>          <button onClick={this.showBasket} disabled={ !this.totalItems() > 0} > Basket { this.totalItems() } </button>
презентационного кода в контейнере быть не должно, нужно выделить кнопку перехода в корзину в отдельный модуль

2019-05-11 07:35 UTC, index01d commented on Week-1/src/containers/CartContainer.js
>        <Fragment>
Фрагмент теперь выглядит лишним

2019-05-11 07:35 UTC, index01d commented on Week-1/src/containers/CartContainer.js
> +      products: products,
не ясно зачем в состоянии корзины список продуктов

2019-05-11 07:35 UTC, index01d commented on Week-1/src/containers/CartContainer.js
> +      products: products,
на взгляд он не используется

2019-05-11 07:35 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
>  const totalCost = (products) =>{
метод может быть предоставлен из контейнера корзины, тогда не нужно будет его дублировать во всех точках приложения, где нужно подсчитать стоимость.

2019-05-11 07:35 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
>  const totalCost = (products) =>{
+ не будет контейнерных расчетов в презентационном компоненте страницы заказа

2019-05-11 07:35 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +            {context.basket ? (<p> Total $ {totalCost(context.basket)} </p>) : '' }
как вариант (чтобы избежать дублирования условия)

```
{
  cart.products ? (
    <>
      cart.products.map((product, i) => (
        <Product  key={i} product={product} style={{ width: 150, height: 100, alt: '' }} />
      )
      <p> Total $ {cart.total} </p>
    </>
 ) : <NotFoundPage />
}
```

2019-05-11 07:35 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +      {context =>(
здесь можно назвать аргумент cart или cartContext, чтобы было более читабельно ниже

2019-05-11 07:35 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +  let products = location.state ? location.state.basket : <NotFoundPage />
на взгляд эта строчка не нужна?

2019-05-11 07:35 UTC, index01d commented on Week-1/src/App.js
> +          <ul>
можно выделить меню в компонент `<Layout>Тут приложение</Layout>`

2019-05-11 07:37 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +            {context.basket ? (<p> Total $ {totalCost(context.basket)} </p>) : '' }
при желании можно позитивный вариант условия выделить в отдельный компонент, отображающий cart целиком со списком и тоталом

2019-05-13 06:46 UTC, index01d approved these changes

2019-05-13 09:12 UTC, merged