Sixth app - React Redux, use redux store to manage products
violentr/reactjs-workshop pull request #6
Opened 2019-05-27 19:22 UTC by violentr

Entry level of playing with React Redux
 - Create Redux store
 - Connect Redux store to the app
- Create Product & Products reducers
- Create actions for Product and Products
- Create actionTypes for Product and Products actions

TODO:
 - Connect ProductContainer to Redux store
 -  Make list of products available on componentDIdMount lifecycle

2019-06-03 10:52 UTC, index01d requested changes

2019-06-03 10:52 UTC, index01d commented on Week-1/src/containers/CartContainer.js
>  class CartContainer extends Component {
CartContainer отсюда и далее уже не выглядит нужным компонентом, можно обернуть redux-connect'ом непосредственно презентационный компонент, который пользуется данными

2019-06-03 10:52 UTC, index01d commented on Week-1/src/containers/CartContainer.js
>          <BasketProvider value={options}>
получается, что с началом использования react-redux старый реакт-контекст для этой задачи нам уже не нужен

2019-06-03 10:52 UTC, index01d commented on Week-1/src/containers/CartContainer.js
> +  totalItems = () => (
можно посчитать в statetToProps

2019-06-03 10:52 UTC, index01d commented on Week-1/src/containers/CartContainer.js
> +  totalCost = () => {
можно посчитать в stateToProps

2019-06-03 10:52 UTC, index01d commented on Week-1/src/containers/CartContainer.js
>      this.props.history.push(checkoutPath())
можно заменить на `<Link to={checkoutPath()}>` в месте использования

2019-06-03 10:52 UTC, index01d commented on Week-1/src/containers/ProductContainer.js
>  class ProductContainer extends Component {
аналогично это старое поведение можно также устранить и посчитать нужные значения в stateToProps

2019-06-04 11:55 UTC, index01d requested changes

2019-06-04 11:55 UTC, index01d commented on Week-1/src/components/Layout.js
>      <Switch>
вот эта часть кстати (`Switch...`) должна была остаться в App.js и сюда передаваться children'aми, ведь это часть настройки роутера а не layout'a

2019-06-04 11:55 UTC, index01d commented on Week-1/src/components/Product/AddToBasket.js
> +import React, {Fragment, Component} from 'react'
небольшой лайфхак: чаще всего работать с презентационными компонентами и с кодом connect() приходится по-отдельности, поэтому чтобы избежать лишних соблазнов лучше держать по отдельности
-AddToBasket
--index.js // connect() и его составляющие (stateToProps, actionsToProps, mergeProps)
--AddToBasket.js // презентационный компонент

2019-06-04 11:55 UTC, index01d commented on Week-1/src/components/Product/AddToBasket.js
> +  state
вот так, к слову о лишних соблазнах, делать не нужно :) передавать в свойствах нужно только реально используемые данные. если из состояния ничего не нужно, то вместо stateToProps можно передать функции connect null, например: `connect(null, actionsToProps)(...)`

2019-06-04 11:55 UTC, index01d commented on Week-1/src/components/Product/Basket.js
> +    totalItems: () => (
на взгляд: не должно быть функцией? можно сразу посчитать

2019-06-04 11:55 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +    totalCost: () => {
не должно быть функцией, тут уже точно нужно выделить код connect, тк уже есть сложные вычисления не относящиеся к презентационной логике. Условно будем считать, что в index у нас лежит контейнерный компонент, созданный с помощью connect()

2019-06-04 11:55 UTC, index01d commented on Week-1/src/components/views/Product/index.js
> +    findById: (products, id) => (
получилось длинная цепочка вызовов с пробрасываемой зависимостью (products), выглядит так, что как минимум первый аргумент не нужен

2019-06-04 11:55 UTC, index01d commented on Week-1/src/components/views/Product/index.js
> +    findById: (products, id) => (
и второй тоже, ведь второй аргумент mapStateToProps = (state, ownProps) и там, в ownProps как раз искомый id, получается можно сразу передать компоненту нужный продукт

2019-06-04 12:00 UTC, index01d requested changes

2019-06-04 12:00 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +      <Fragment>
зачем два вложенных фрагмента?

2019-06-04 12:00 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
>  import { imageAttributes } from '~/src/shared/helper.js'
выглядит чуть сомнительно, список многовато знает о настройках зависимостей карточки;  нужно или надстраивать CatalogCard или вообще вхардкодить в ProductCard, если аттрибуты одинаковы для всех.

2019-06-04 12:00 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +          { listProducts(this.props) }
выделение listProducts теперь выглядит избыточным, весь этот код вполне симпатично смотрелся бы и здесь

2019-06-04 12:00 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +class CheckoutPage extends Component {
на взгляд компонент мог бы быть обычным функциональным `({ items, totalCost }) => (<..someJSX>)`

2019-06-04 18:19 UTC, violentr commented on Week-1/src/components/views/Checkout/index.js
> +    totalCost: () => {
> не должно быть функцией, тут уже точно нужно выделить код connect, тк уже есть сложные вычисления не относящиеся к презентационной логике. Условно будем считать, что в index у нас лежит контейнерный компонент, созданный с помощью connect()

@index01d не очень понятен комментарий, что здесь не верно ? нужно сделать презентационный компонент ? и index.js сделать connect кодом ?

2019-06-04 19:31 UTC, index01d commented on Week-1/src/components/views/Checkout/index.js
> +    totalCost: () => {
конкретно здесь имеется ввиду, что нет смысла totalCost делать функцией:

```
totalCost: state.basket.items.reduce((total, product) => total + product.price)
```

по факту решает задачу

2019-06-05 15:09 UTC, index01d requested changes

2019-06-05 15:09 UTC, index01d commented on Week-1/src/components/Product/Basket.js
> +          <button disabled={ !this.props.totalItems > 0}>
== 0? условие какое-то неправильное

2019-06-05 15:09 UTC, index01d commented on Week-1/src/components/views/Products/Catalog.js
> +          <ProductAddToBasket key={i} item={product} addProduct={addProduct} />
каталог теперь слишком много знает о логике корзины. ProductAddToBasket можно же снабдить собственным контейнером и передавать здесь в свойствах только сам product (к тому же стоит свойство назвать product={product}, чтобы не изобретать разных имен одного и того же и не вводить коллег в заблуждение:))

2019-06-05 15:09 UTC, index01d commented on Week-1/src/components/views/Products/index.js
>  class ProductsPage extends Component {
выглядит теперь лишним компонентом, который ничего не делает, можно напрямую здесь приконнектить 
`export default connect(mapStateToProps, actionToProps)(Catalog)` и будет ок

2019-06-05 15:09 UTC, index01d commented on Week-1/src/components/views/Products/Catalog.js
> +          <ProductAddToBasket key={i} item={product} addProduct={addProduct} />
тогда ProductAddToBasket вполне может себе позволить быть частью ProductCard

2019-06-05 18:51 UTC, violentr commented on Week-1/src/components/Product/Basket.js
> +          <button disabled={ !this.props.totalItems > 0}>
> == 0? условие какое-то неправильное
согласен, че то я здесь намудрил ;-)

2019-06-05 19:31 UTC, violentr commented on Week-1/src/components/views/Products/Catalog.js
> +          <ProductAddToBasket key={i} item={product} addProduct={addProduct} />
> тогда ProductAddToBasket вполне может себе позволить быть частью ProductCard

@index01d если я сделаю  ProductAddToBasket  частью компонента ProductCard то у меня AddToBasket button будет везде  и в Checkout page
а мне это не надо ;-)

2019-06-06 09:41 UTC, index01d approved these changes

2019-06-06 19:33 UTC, merged