Seventh app
violentr/reactjs-workshop pull request #7
Opened 2019-06-11 21:19 UTC by violentr

- Save current basket state to the local storage
- Create middleware (which outputs current selected product to console) 
   save current basket state to the local storage
- Create middleware for all create actions.

2019-06-14 13:22 UTC, index01d requested changes
Загрузку данных из localStorage нужно делать в middleware, а не в коде компонентов

2019-06-14 13:22 UTC, index01d commented on Week-1/src/store/index.js
> +const basketMiddleware = (store) => (next) => (action) => {
нужно выделить в отдельный модуль, loadState нужно делать здесь

2019-06-14 14:23 UTC, violentr commented on Week-1/src/store/index.js
> +const basketMiddleware = (store) => (next) => (action) => {
@index01d не очень понятен комментарий, я понял что функцию надо вынести в отдельный файл
но мне не понятно что надо делать с loadState() ? что я делаю не верно ?

2019-06-14 16:06 UTC, index01d commented on Week-1/src/store/index.js
> +const basketMiddleware = (store) => (next) => (action) => {
loadState нужно вызывать в middleware при обработке action'a LOAD_CART, или чего-то подобного. и один раз устанавливать состояние в reducer'e. А затем использовать это состояние в приложении с помощью connect()

2019-06-14 16:07 UTC, index01d commented on Week-1/src/store/index.js
> +const basketMiddleware = (store) => (next) => (action) => {
аналогично подобная работа с побочным эффектом (загрузка данных по API или localStorage это побочный эффект) реализована в https://github.com/violentr/reactjs-workshop/blob/seventh_app/Week-1/src/middleware/Api.js

2019-06-15 14:25 UTC, index01d requested changes

2019-06-15 14:25 UTC, index01d commented on Week-1/src/store/index.js
> +const persistedState = loadState()
можно так, или, что корректнее, нужно прямо в BasketMiddleware перехватывать LOAD_CART и снабжать action списком продуктов из loadState(), после чего с помощью next(action) продолжать обработку. Корректнее, потому что в этом модуле останется только инициализация store'a и ничего более

2019-06-16 05:58 UTC, index01d approved these changes

2019-06-16 05:58 UTC, index01d commented on Week-1/src/middleware/cart.js
> +import {loadState} from '~/src/shared/cartPersistence.js'
коль скоро это используется только в middleware, то можно перенести модуль
```
- middleware
-- cart
--- cartPersistence.js
--- index.js
```

2019-06-16 14:51 UTC, merged